# File Path: pubspec.yaml

name: brahma_muhurta
description: A Flutter app to calculate Brahma Muhurta times based on your location.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6

  # Location Services
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

  # Notifications
  flutter_local_notifications: ^19.4.2

  # Timezone (single entry, using latest version)
  timezone: 0.10.1

  # State Management
  provider: ^6.1.1

  # Date/Time utilities
  intl: ^0.20.2

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Add this for icon generation
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # App Icons and Assets
  assets:
    - assets/images/
    - assets/icon/

# Icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#6B4E71"  # Your primary color
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
